server:
  port: 9000

spring:
  application:
    name: mtogo-api-gateway

  cloud:
    gateway:
      routes:

        # REST API routes (already working)
        - id: restaurants
          uri: http://backend:8080
          predicates:
            - Path=/api/restaurants/**

        - id: orders
          uri: http://backend:8080
          predicates:
            - Path=/api/orders/**

        # SWAGGER UI forwarder
        - id: swagger-ui
          uri: http://backend:8080
          predicates:
            - Path=/swagger-ui/**

        # Swagger HTML entrypoint
        - id: swagger-index
          uri: http://backend:8080
          predicates:
            - Path=/swagger-ui.html

        # OpenAPI JSON
        - id: openapi
          uri: http://backend:8080
          predicates:
            - Path=/v3/api-docs/**
